spring:
  application:
    name: api-gateway

server:
  port: 8080

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: recharge-service
          uri: lb://recharge-service
          predicates:
            - Path=/api/recharge/**
        - id: operator-service
          uri: lb://operator-service
          predicates:
            - Path=/api/operators/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/audit/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/