spring:
  application:
    name: audit-service

  server:
     port: 8086

datasource:
  url: jdbc:h2:mem:auditdb
  username: sa
  password: password
  driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

